baseURL = "https://ease.ml/"
languageCode = 'en-us'
title = 'ease.ml'
theme = "nofancy-custom"

googleAnalytics = "G-15VE4F9Z07"

[author]
    name = "DS3 Lab"
    homepage = "https://ds3lab.inf.ethz.ch/"
    github = "DS3Lab"
    twitter = "ds3lab"

[markup.goldmark.renderer]
    unsafe= true