baseURL = "https://ease.ml/"
languageCode = 'en-us'
title = 'ease.ml'
theme = "cotton-sky"

googleAnalytics = "G-15VE4F9Z07"

[author]
    name = "DS3 Lab"
    homepage = "https://ds3lab.inf.ethz.ch/"
    github = "DS3Lab"
    twitter = "ds3lab"

[markup.goldmark.renderer]
    unsafe= true

[imaging]
quality = 100

# Menu links
[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Components"
    pre = "components"
    url = "/components/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    pre = "publications"
    url = "/publications/"
    weight = 3
